services:
#------------------------------------------------------------
# 
  api:
    build: 
      context: ./api
      dockerfile: Dockerfile
    container_name: laravel-api
    ports:
      - "8000:80"
    volumes:
      - ./api:/var/www/html
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_DATABASE=kelnik
      - DB_USERNAME=root
      - DB_PASSWORD=secret
    networks:
      kelnik-network:
        aliases:
          - api.local
    entrypoint: /var/www/html/docker/entrypoint.sh
    # healthcheck:
    #     test: ["CMD", "curl", "-f", "http://localhost/api/health"]
    #     interval: 30s
    #     timeout: 10s
    #     retries: 3
#------------------------------------------------------------
# 
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vue-frontend
    ports:
      - "3000:80"
    depends_on:
      - api
    networks:
      kelnik-network:
        aliases:
          - frontend.local
    volumes:
      - ./frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VUE_APP_API_URL=http://api/api/v1
      - VITE_API_URL=http://api/api/v1

#------------------------------------------------------------
# 
  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=kelnik
    ports:
      - "3306:3306"
    networks:
      - kelnik-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

  

#------------------------------------------------------------
volumes:
  db_data:

#------------------------------------------------------------
networks:
  kelnik-network:
    driver: bridge